"""modified votes table

Revision ID: 24de94f65ae9
Revises: c56f947e1f4e
Create Date: 2023-04-19 21:04:45.133474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24de94f65ae9'
down_revision = 'c56f947e1f4e'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('president_id', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('vice_president_id', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('secretary_id', sa.Integer(), nullable=True))
    op.drop_column('votes', 'vice_president')
    op.drop_column('votes', 'president')
    op.drop_column('votes', 'secretary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('secretary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('president', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('vice_president', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('votes', 'secretary_id')
    op.drop_column('votes', 'vice_president_id')
    op.drop_column('votes', 'president_id')
    # ### end Alembic commands ###
