"""added image column to candidate table

Revision ID: 9209c3eed6fb
Revises: 0b7a6ac459c1
Create Date: 2023-01-31 22:47:54.779264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9209c3eed6fb'
down_revision = '0b7a6ac459c1'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'image')
    # ### end Alembic commands ###
