"""added votes column to candidates

Revision ID: c56f947e1f4e
Revises: 9209c3eed6fb
Create Date: 2023-02-17 20:01:22.125806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56f947e1f4e'
down_revision = '9209c3eed6fb'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'votes')
    # ### end Alembic commands ###
